### PR TITLE
Utilize Spree::Preferences to hold avatax information.

### PR DESCRIPTION
**Pull request by acreilly**
Remove Spree::AvalaraPreference and replace with Spree::AvataxConfiguration

### CODE REVIEW

**Comment by ericsaupe** [comment]
We are a bit worried about placing usernames/passwords/keys in databases instead of simply using Environment variables like we do with other sensitive information like database information, rails secrets, etc.

Thoughts?

**Comment by acreilly** [comment]
For certification purposes, Avatax requires us to allow the user to be able to change that information in the admin panel.
image

https://developer.avalara.com/avatax/certification/

**Comment by ericsaupe** [comment]
Huh, well I guess we're stuck there. That's interesting that is their policy for secrets and logins but OK. I think this PR looks fine other than my concerns expressed above.

**Comment by ericsaupe** [comment]
Is there a way to encrypt that information then?

**Comment by ericsaupe** [comment]
Probably just hashed like a password field. Basically if someone has access to the database we don't want them to have any login information.

**Comment by ericsaupe** [comment]
@acreilly talking it over with my team we've decided this isn't _that_ big of a deal to hash those passwords. If someone had access to your database they would have access to your avatax account as well but that may be a smaller concern overall? What do you think? Might not be worth hashing is what I'm trying to say.

**Comment by skukx** [comment]
Hashing can always be undone (Not Secure).  Encryption requires a key (Secure). However the amount of work to do so in my opinion would not be worth the gain.  Avatax contains the same information as the solidus database so if a database has been compromised, having access to avatax doesn't present an intruder with any information they don't already have.

**Comment by acreilly** [comment]
Yeah, I don't think it is worth putting the time in to come with the gem. I think if people want it, they can create that ability in their app or fork.

**Pull request merged**
