### PR TITLE
Remove dotenv dependency

### PR DESCRIPTION
**Pull request by cedum**
~Load the dotenv vars before loading the dummy app in tests. Otherwise, when `app/models/spree/avatax_configuration.rb` file is loaded the env vars from dotenv are still `nil`.
Also, exclude dotenv from being loaded on TravisCI. ENV vars are set directly by Travis.~

Removes completely `dotenv`. See discussion below.

TODO:

- [ ] update wiki: https://github.com/boomerdigital/solidus_avatax_certified/wiki/Installation#environment-variables

### CODE REVIEW

**Comment by aldesantis** [comment]
@cedum I think you can remove the code that skips Dotenv in Travis, since:

- Dotenv will still use the environment variables, if they are present
- We don't have any environment variables in Travis anymore (#140)
- `.env` is `.gitignore`d, so it won't get into the repo/Travis anyway

**Comment by dhonig** [comment]
Closing...

**Comment by cedum** [comment]
@aldesantis agree.
@dhonig can we please reopen this PR? There's still the issue with dotenv ENV vars loading precedence.

**Comment by dhonig** [comment]
I closed it since the plugin itself should have no knowledge at all of .env.  If the main app does thats fine, but it should just be env vars at the plugin level

**Comment by aldesantis** [comment]
@dhonig should we remove Dotenv entirely from the gem? I think that would make sense, how to load configuration should be a concern of the main app, not the gem.

**Comment by dhonig** [comment]
@aldesantis  we should absolutely remove Dotenv entirely from the GEM.   When top level development concerns leak down to plugins it just leads to confusion and more issues IMHO.
Perhaps its needed in testing but I'd say not even then really as the right environment can just be set in the test support.

**Comment by aldesantis** [comment]
@dhonig makes sense. @cedum could you update this PR to remove Dotenv entirely?

**Comment by aldesantis** [comment]
Thanks @cedum!

**Pull request merged**
