### PR TITLE
Replace Deface Ruby with Deface DSL

### PR DESCRIPTION
**Pull request by tmtrademarked**
This PR replaces the use of the Deface Ruby overrides with the Deface DSL. This makes this gem compatible with Rails 7.1, since the Deface overrides tend to break Zeitwerk naming conventions.

### CODE REVIEW

**Comment by tmtrademarked** [comment]
The spec failures here *appear* to not be related to my changes - but I'm not well enough versed in how these specs are set up to feel confident. Anyone have any suggestions on how to fix this?

**Comment by daniel-honig-clearscale** [comment]
@tmtrademarked   thanks for the PR.  
Did you look into this line on the errors?


LoadError:
  cannot load such file -- spree/tax/tax_helpers

**Comment by tmtrademarked** [comment]
Yeah, I saw that line - what I can't figure out is how changing the deface files would have changed anything about that. As I understand it, that is requiring the `Spree::Tax::TaxHelpers` from Solidus core - right?

**Comment by dhonig** [comment]
> Yeah, I saw that line - what I can't figure out is how changing the deface files would have changed anything about that. As I understand it, that is requiring the `Spree::Tax::TaxHelpers` from Solidus core - right?

Yes agreed that seems funny.   I suppose we need to see if something funny is happening with Zeitwerk and in the autoloading......

**Comment by tmtrademarked** [comment]
FWIW, when I run these specs locally on master, it seems like they fail with the same error:
```
/Users/tom.wilson/.rbenv/versions/3.1.2/bin/ruby -I/Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.2/lib:/Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rspec-support-3.12.1/lib /Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.2/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
Provide a CODECOV_TOKEN environment variable to enable Codecov uploads

An error occurred while loading ./spec/models/solidus_avatax_certified/line_spec.rb. - Did you mean?
                    rspec ./spec/models/solidus_avatax_certified/address_spec.rb
                    rspec ./spec/models/solidus_avatax_certified/avatax_log_spec.rb
                    rspec ./spec/models/solidus_avatax_certified/request/base_spec.rb

Failure/Error: require 'spree/tax/tax_helpers'

LoadError:
  cannot load such file -- spree/tax/tax_helpers
  ```

**Comment by kennyadsl** [comment]
That [`require`](https://github.com/boomerdigital/solidus_avatax_certified/blob/9635709931a84875c9c421bb39e4209074eb375b/app/models/solidus_avatax_certified/line.rb#L3) might not be necessary anymore. Can you try removing it?

**Comment by tmtrademarked** [comment]
I gave that a try over in [separate PR]() to see what happened, because my understanding is that the manual `require` *shouldn't* be required any more. It looks like there's still something not quite happy, though:
```
An error occurred in an `after(:suite)` hook.
Failure/Error: raise ZeitwerkNameError, message

ZeitwerkNameError:
  Zeitwerk raised the following error when trying to eager load your extension:

  uninitialized constant Spree::Admin::Shared::ConfigurationMenu

  This most likely means that your extension's file structure is not
  compatible with the Zeitwerk autoloader.
  Refer to https://github.com/solidusio/solidus_support#engine-extensions in
  order to update the file structure to match Zeitwerk's expectations.
# /home/circleci/project/vendor/bundle/main/ruby/3.2.0/gems/solidus_dev_support-2.9.0/lib/solidus_dev_support/rspec/rails_helper.rb:86:in `rescue in block (2 levels) in <top (required)>'
# /home/circleci/project/vendor/bundle/main/ruby/3.2.0/gems/solidus_dev_support-2.9.0/lib/solidus_dev_support/rspec/rails_helper.rb:62:in `block (2 levels) in <top (required)>'
# /home/circleci/project/vendor/bundle/main/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
# /home/circleci/project/vendor/bundle/main/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
# /home/circleci/project/vendor/bundle/main/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:372:in `run'
# /home/circleci/project/vendor/bundle/main/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/configuration.rb:2157:in `block in run_suite_hooks'
# /home/circleci/project/vendor/bundle/main/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/configuration.rb:2155:in `each'
# /home/circleci/project/vendor/bundle/main/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/configuration.rb:2155:in `run_suite_hooks'
# /home/circleci/project/vendor/bundle/main/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/configuration.rb:2073:in `with_suite_hooks'
# /home/circleci/project/vendor/bundle/main/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:116:in `block in run_specs'
# /home/circleci/project/vendor/bundle/main/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/reporter.rb:74:in `report'
# /home/circleci/project/vendor/bundle/main/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:115:in `run_specs'
# /home/circleci/project/vendor/bundle/main/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:89:in `run'
# /home/circleci/project/vendor/bundle/main/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:71:in `run'
# /home/circleci/project/vendor/bundle/main/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:45:in `invoke'
# /home/circleci/project/vendor/bundle/main/ruby/3.2.0/gems/rspec-core-3.12.2/exe/rspec:4:in `<main>'
# 
#   Showing full backtrace because every line was filtered out.
#   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
#   RSpec::Configuration#backtrace_inclusion_patterns for more information.
# ------------------
# --- Caused by: ---
# NameError:
#   uninitialized constant Spree::Admin::Shared::ConfigurationMenu
#   /home/circleci/project/vendor/bundle/main/ruby/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/helpers.rb:135:in `const_get'
```

**Comment by kennyadsl** [comment]
@dhonig can we merge this and the other new PR from @tmtrademarked? I can help if you provide permissions. Thanks in advance!

**Comment by dhonig** [comment]
> @dhonig can we merge this and the other new PR from @tmtrademarked? I can help if you provide permissions. Thanks in advance!

Sure so long as we are sure that it is backwards compatible.    @kennyadsl , you should have write permissions already....Will make sure you still have permissions for this now.

**Comment by dhonig** [comment]
> > @dhonig can we merge this and the other new PR from @tmtrademarked? I can help if you provide permissions. Thanks in advance!
> 
> Sure so long as we are sure that it is backwards compatible. @kennyadsl , you should have write permissions already....Will make sure you still have permissions for this now.

You should have access now.

**Comment by kennyadsl** [comment]
Before merging, we are fixing something on Solidus Core to let specs pass on the older versions' build as well. When we've done I will re-run specs here to be sure this change is backward compatible with all supported Solidus versions.

**Comment by dhonig** [comment]
> Before merging, we are fixing something on Solidus Core to let specs pass on the older versions' build as well. When we've done I will re-run specs here to be sure this change is backward compatible with all supported Solidus versions.

Sounds good! your write access is added.

**Comment by kennyadsl** [comment]
All green, merging!

**Review by kennyadsl — APPROVED** [review]

**Pull request merged**
